# Generated by Django 3.2.15 on 2022-10-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_watchedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchedModel',
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='is_watched',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
