# Generated by Django 3.2.15 on 2022-10-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_remove_moviemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('producer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'watched',
            },
        ),
    ]
