# Generated by Django 3.2.15 on 2022-11-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20221022_1320'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviemodel',
            table='movielist',
        ),
    ]
