# Generated by Django 3.2.15 on 2022-11-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_alter_moviemodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='is_watched',
        ),
    ]
