# Generated by Django 3.2.15 on 2022-11-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_moviemodel_is_watched'),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='watched_movies',
            field=models.ManyToManyField(to='list.MovieModel'),
        ),
    ]
